# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# Variables file for broadsage.github role
# These variables have higher precedence than defaults

# Path where the GitHub configuration will be deployed
github_project_path: "{{ playbook_dir }}"

# GitHub API configuration (optional)
# github_api_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
# github_api_base_url: "https://api.github.com"

# Advanced GitHub configurations
github_auto_labeling:
  enabled: true
  rules:
    - label: "bug"
      title_regex: "^(bug|fix|error|issue)"
    - label: "enhancement"
      title_regex: "^(feat|feature|enhancement)"
    - label: "documentation"
      body_regex: "documentation|docs|readme"

# CodeOwners configuration
github_codeowners:
  - path: "*"
    owners:
      - "@{{ github_organization }}/maintainers"
  - path: ".github/"
    owners:
      - "@{{ github_organization }}/devops"
  - path: "docs/"
    owners:
      - "@{{ github_organization }}/documentation"

# Update repository settings via API (requires github_api_token)
github_update_repo_settings: false

# Validation settings
github_validate_workflows: true
github_validate_templates: true