# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: 2
# Check for updates to GitHub Actions every week
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow Dependabot to open PRs for GitHub Actions updates
    open-pull-requests-limit: 10
    
  - package-ecosystem: docker
    directory: /broadsage/nginx/1.29/debian-12
    schedule:
      interval: daily
