# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

# Container Security and Quality Configuration

# Hadolint configuration for Dockerfile linting

---
ignored:
  - DL3008 # Allow apt-get install without specific versions in base images
  - DL3009 # Allow keeping apt lists for debugging in development images

trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io
  - quay.io
