# Container Security and Quality Configuration

# Hadolint configuration for Dockerfile linting
ignored:
  - DL3008 # Allow apt-get install without specific versions in base images
  - DL3009 # Allow keeping apt lists for debugging in development images

trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io
  - quay.io
