# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

# configurations
[[annotations]]
path = [".github/PULL_REQUEST_TEMPLATE.md",".commitlintrc.json",".markdownlint.json",".github/auto-label-config.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage <opensource@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"

# images etc
[[annotations]]
path = ["assets/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage <opensource@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"

# bitnami configuration files - using glob patterns
[[annotations]]
path = ["library/**/.bitnami_components.json", "library/**/licenses.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage <opensource@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"

# bitnami template files - using glob patterns
[[annotations]]
path = ["library/**/bitnami-templates/*.tpl"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage <opensource@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"