# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

# configurations
[[annotations]]
path = [".github/CODEOWNERS",".github/PULL_REQUEST_TEMPLATE.md",".github/auto-label-config.json",".commitlintrc.json",".markdownlint.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"

# images etc
[[annotations]]
path = ["assets/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>"
SPDX-License-Identifier = "Apache-2.0"
