# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/broadsage-containers/docker-template/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/broadsage-containers/docker-template/security/advisories/new
    about: Please report security vulnerabilities privately through GitHub Security Advisories
  - name: 📖 Documentation
    url: https://github.com/broadsage-containers/docker-template/blob/main/README.md
    about: Check our documentation for guides and information
