# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
name: ❓ Question & Support
description: Ask a question or get help
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We're here to help. 🤝

        **Before asking**: Please check our documentation and existing discussions.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      options:
        - label: I have read the [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: I have reviewed the documentation
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Installation/Setup
        - Usage/How-to
        - Configuration
        - Troubleshooting
        - Best practices
        - Development/Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "Ask your question here..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context or background information
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Any relevant system information?

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: "Screenshots, logs, configuration files, etc."
