# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# Default variables for broadsage.github role

# Project Information
github_project_name: "{{ ansible_project_name | default('my-project') }}"
github_project_description: "{{ ansible_project_description | default('A containerized application') }}"
github_organization: "{{ ansible_organization | default('broadsage-containers') }}"

# GitHub Configuration
github_default_branch: main
github_license: Apache-2.0
github_copyright_holder: "Broadsage Corporation <containers@broadsage.com>"
github_copyright_year: "2025"

# Repository Settings
github_visibility: public
github_enable_issues: true
github_enable_projects: true
github_enable_wiki: false
github_allow_squash_merge: true
github_allow_merge_commit: false
github_allow_rebase_merge: true
github_delete_branch_on_merge: true
github_enable_auto_merge: true

# Branch Protection Settings
github_branch_protection:
  enabled: true
  enforce_admins: true
  required_status_checks:
    strict: true
    contexts:
      - "mega-linter"
      - "dependency-review"
      - "scorecard-analysis"
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    restrict_dismissals: false

# Issue Templates
github_issue_templates:
  - name: bug
    enabled: true
  - name: feature
    enabled: true
  - name: question
    enabled: true
  - name: config
    enabled: true

# GitHub Workflows
github_workflows:
  commit:
    enabled: true
    name: "Commit Validation"
  dependency_review:
    enabled: true
    name: "Dependency Review"
  mega_linter:
    enabled: true
    name: "Code Quality & Security"
  pr_validate:
    enabled: true
    name: "Pull Request Validation"
  pr_publish:
    enabled: true
    name: "Pull Request Publishing"
  scorecard:
    enabled: true
    name: "Security Scorecard"
  stale:
    enabled: true
    name: "Stale Issues & PRs"
  label_management:
    enabled: true
    name: "Label Management"
  license:
    enabled: true
    name: "License Compliance"
  dependabot_auto_merge:
    enabled: true
    name: "Dependabot Auto Merge"

# Dependabot Configuration
github_dependabot:
  enabled: true
  package_ecosystems:
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10

# Security Configuration
github_security:
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
    dependency_graph:
      status: enabled
    dependabot_security_updates:
      status: enabled

# Community Health Files
github_community_files:
  code_of_conduct:
    enabled: true
    template: "citizen-code-of-conduct"
  contributing:
    enabled: true
  security:
    enabled: true
  support:
    enabled: true
  governance:
    enabled: true
  maintainers:
    enabled: true

# Labels Configuration
github_labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "priority:high"
    color: "ff0000"
    description: "High priority issue"
  - name: "priority:medium"
    color: "ff9500"
    description: "Medium priority issue"
  - name: "priority:low"
    color: "0e8a16"
    description: "Low priority issue"
  - name: "status:in-progress"
    color: "fbca04"
    description: "Currently being worked on"
  - name: "status:needs-review"
    color: "bfdadc"
    description: "Needs review from maintainers"
  - name: "type:breaking-change"
    color: "b60205"
    description: "Breaking change"
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"

# File Templates
github_file_templates:
  pull_request_template: true
  issue_templates: true
  workflows: true
  community_health: true