# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# Configuration file for MegaLinter.
# See configuration options at https://oxsecurity.github.io/megalinter/configuration/ and more in each linter documentation.

# General
PRINT_ALPACA: false
APPLY_FIXES: all
LOG_LEVEL: INFO # Add explicit log level
LOG_FILE: mega-linter.log # Explicit log file

DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
VALIDATE_ALL_CODEBASE: true # Set to false for better PR performance, workflow handles this
FAIL_WITHOUT_ERRORS: false # Don't fail if no lintable files are found

# Reporter options
CLEAR_REPORT_FOLDER: true
EMAIL_REPORTER: false
TEXT_REPORTER: true
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
GITLAB_COMMENT_REPORTER: false
UPDATED_SOURCES_REPORTER: true

# Lint specific settings
ENABLE_LINTERS:
  [
    BASH_SHELLCHECK,
    BASH_SHFMT,
    MARKDOWN_MARKDOWNLINT,
    YAML_PRETTIER,
    JSON_JSONLINT,
    JSON_PRETTIER,
    ACTION_ACTIONLINT,
    REPOSITORY_GITLEAKS,
    CREDENTIALS,
    PYTHON_PYLINT,
    PYTHON_FLAKE8,
    PYTHON_BLACK,
    PYTHON_ISORT,
  ]

BASH_SHFMT_ARGUMENTS: -i 2
BASH_SHFMT_FILE_EXTENSIONS: [.sh]
BASH_SHELLCHECK_FILE_EXTENSIONS: [.sh]
PYTHON_PYLINT_FILE_EXTENSIONS: [.py]
PYTHON_FLAKE8_FILE_EXTENSIONS: [.py]
PYTHON_BLACK_FILE_EXTENSIONS: [.py]
PYTHON_ISORT_FILE_EXTENSIONS: [.py]

# JSON linter settings
JSON_JSONLINT_FILE_EXTENSIONS: [.json]
JSON_PRETTIER_FILE_EXTENSIONS: [.json]
