# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
services:
  nginx:
    image: docker.io/bitnami/nginx:1.29
    ports:
      - "80:8080"
