# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
services:
  nginx:
    image: ghcr.io/broadsage/nginx:1.29
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # volumes:
    #   # Uncomment to mount custom configuration
    #   # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #   # - ./html:/usr/share/nginx/html:ro
