# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

# Simplified Cosign Verification Policy for Broadsage Container Consumers
# This policy focuses on signature verification only.
# Attestations (SBOM, build provenance) are verified through GitHub's native system.

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: broadsage-consumer-policy
  annotations:
    description: "Consumer-friendly signature verification policy for Broadsage containers"
    version: "2.0.0"
    documentation: "https://github.com/broadsage/containers/docs/image-verification.md"
spec:
  images:
    # Only Broadsage official images
    - glob: "ghcr.io/broadsage/*"

  authorities:
    # Only accept production releases
    - name: "broadsage-official-releases"
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/broadsage/containers/.github/workflows/release-pipeline.yml@refs/heads/main"
        ctlog:
          url: https://rekor.sigstore.dev

  # Warn mode for consumer flexibility
  mode: warn

  # Require transparency log entries
  requireRekorBundle: true

  # Signature verification only - attestations handled by GitHub
  policy:
    - match:
        - glob: "ghcr.io/broadsage/*"
      requirements:
        - authorities: ["broadsage-official-releases"]
