# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

# Cosign Cluster Image Policy for Broadsage Containers
# This policy focuses on signature verification only.
# Attestations (SBOM, build provenance) are handled by GitHub Actions natively.

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: broadsage-containers-policy
  labels:
    policy.sigstore.dev/version: v1beta1
    security.broadsage.com/level: enterprise
spec:
  images:
    # Broadsage container images on GitHub Container Registry
    - glob: "ghcr.io/broadsage/*"
    # Future registry support
    - glob: "docker.io/broadsage/*"
    - glob: "quay.io/broadsage/*"

  authorities:
    # Production releases from main branch
    - name: "broadsage-production-releases"
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          # Release pipeline workflow
          - issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/broadsage/containers/.github/workflows/release-pipeline.yml@refs/heads/main"
        ctlog:
          url: https://rekor.sigstore.dev

    # Approved PR builds (for testing)
    - name: "broadsage-approved-pr-builds"
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          # PR publish workflow
          - issuer: "https://token.actions.githubusercontent.com"
            subjectRegExp: "^https://github.com/broadsage/containers/.github/workflows/pr-publish.yml@refs/heads/.*"
        ctlog:
          url: https://rekor.sigstore.dev

  # Policy mode - enforce for production, warn for development
  mode: enforce

  # Additional security requirements
  requireRekorBundle: true

  # Match specific image patterns with signature-only verification
  policy:
    # Production images require signature verification only
    - match:
        - glob: "ghcr.io/broadsage/*:v*" # Version tags
        - glob: "ghcr.io/broadsage/*:latest" # Latest tags
      requirements:
        - authorities: ["broadsage-production-releases"]

    # Development/PR images with relaxed requirements
    - match:
        - glob: "ghcr.io/broadsage/*:pr-*"
        - glob: "ghcr.io/broadsage/*:dev-*"
      requirements:
        - authorities: ["broadsage-approved-pr-builds"]
