# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# Main tasks file for broadsage.github role

- name: "Create .github directory structure"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ github_project_path }}/.github"
    - "{{ github_project_path }}/.github/workflows"
    - "{{ github_project_path }}/.github/ISSUE_TEMPLATE"
  tags:
    - github
    - directories

- name: "Deploy GitHub workflows"
  ansible.builtin.template:
    src: ".github/workflows/{{ item.key }}.yml.j2"
    dest: "{{ github_project_path }}/.github/workflows/{{ item.key }}.yml"
    mode: '0644'
  loop: "{{ github_workflows | dict2items }}"
  when: item.value.enabled | default(false)
  tags:
    - github
    - workflows

- name: "Deploy GitHub issue templates"
  ansible.builtin.template:
    src: ".github/ISSUE_TEMPLATE/{{ item.name }}.yml.j2"
    dest: "{{ github_project_path }}/.github/ISSUE_TEMPLATE/{{ item.name }}.yml"
    mode: '0644'
  loop: "{{ github_issue_templates }}"
  when: item.enabled | default(false)
  tags:
    - github
    - issue-templates

- name: "Deploy pull request template"
  ansible.builtin.template:
    src: ".github/PULL_REQUEST_TEMPLATE.md.j2"
    dest: "{{ github_project_path }}/.github/PULL_REQUEST_TEMPLATE.md"
    mode: '0644'
  when: github_file_templates.pull_request_template | default(true)
  tags:
    - github
    - pr-template

- name: "Deploy dependabot configuration"
  ansible.builtin.template:
    src: ".github/dependabot.yml.j2"
    dest: "{{ github_project_path }}/.github/dependabot.yml"
    mode: '0644'
  when: github_dependabot.enabled | default(true)
  tags:
    - github
    - dependabot

- name: "Deploy CODEOWNERS file"
  ansible.builtin.template:
    src: ".github/CODEOWNERS.j2"
    dest: "{{ github_project_path }}/.github/CODEOWNERS"
    mode: '0644'
  when: github_codeowners is defined and github_codeowners | length > 0
  tags:
    - github
    - codeowners

- name: "Deploy auto-label configuration"
  ansible.builtin.template:
    src: ".github/auto-label-config.json.j2"
    dest: "{{ github_project_path }}/.github/auto-label-config.json"
    mode: '0644'
  when: github_auto_labeling.enabled | default(true)
  tags:
    - github
    - auto-labeling

- name: "Create community health files"
  ansible.builtin.template:
    src: "community/{{ item.key | upper }}.md.j2"
    dest: "{{ github_project_path }}/{{ item.key | upper }}.md"
    mode: '0644'
  loop: "{{ github_community_files | dict2items }}"
  when: item.value.enabled | default(false)
  tags:
    - github
    - community

- name: "Display GitHub role deployment summary"
  ansible.builtin.debug:
    msg:
      - "GitHub role deployment completed for: {{ github_project_name }}"
      - "Organization: {{ github_organization }}"
      - "License: {{ github_license }}"
      - "Workflows enabled: {{ github_workflows | dict2items | selectattr('value.enabled', 'equalto', true) | list | length }}"
      - "Issue templates: {{ github_issue_templates | selectattr('enabled', 'equalto', true) | list | length }}"
      - "Branch protection: {{ 'Enabled' if github_branch_protection.enabled else 'Disabled' }}"
  tags:
    - github
    - summary