# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage Corporation <containers@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  role_name: github
  namespace: broadsage
  author: Broadsage Corporation
  description: Ansible role for GitHub repository setup and configuration
  company: Broadsage Corporation
  
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  
  # Choose a valid license ID from https://spdx.org - you can use the identifier from
  license: Apache-2.0
  
  min_ansible_version: "2.12"
  
  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:
  
  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - github
    - git
    - repository
    - workflow
    - ci
    - cd
    - automation
    - templates
    - issues
    - collaboration

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.