# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
name: Conform DCO (--Sign-off)
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  signoff:
    runs-on: ubuntu-latest
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a #v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup main branch without switching current branch
        run: git fetch origin main:main

      - name: Conform Action
        uses: siderolabs/conform@a316d3d13e82ac5f8d2eae42a734f8a885cddb15 # v0.1.0-alpha.29
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
