# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "[Support] Setup Repository Labels"

on:
  workflow_dispatch:
    # Manual trigger only - run once to set up labels

# Use restrictive default permissions
permissions:
  contents: read

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    name: Setup standard labels
    # Job-level permissions for label management
    permissions:
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Setup standard repository labels
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const labels = [
              // TYPE LABELS - What kind of change
              { name: 'type: fix', color: 'ff6b6b', description: 'Bug fixes, security patches, corrections' },
              { name: 'type: feature', color: '00d4aa', description: 'New functionality, enhancements' },
              { name: 'type: docs', color: '0075ca', description: 'Documentation only changes' },
              { name: 'type: maintenance', color: '7f8c8d', description: 'Dependencies, refactoring, tooling' },
              
              // PRIORITY LABELS - How urgent
              { name: 'priority: critical', color: 'b60205', description: 'Security vulnerabilities, breaking issues' },
              { name: 'priority: high', color: 'ff9500', description: 'Important but not breaking' },
              
              // STATUS LABELS - Current state
              { name: 'status: needs-info', color: 'f9d71c', description: 'Waiting for more information' },
              { name: 'status: ready', color: '0e8a16', description: 'Ready for review/merge' },
              { name: 'status: wip', color: 'fbca04', description: 'Work in progress' },
              { name: 'status: blocked', color: 'c5def5', description: 'Blocked by external factors' },
              
              // SPECIAL LABELS - Keep essential ones
              { name: 'good first issue', color: '7057ff', description: 'Good for newcomers' },
              { name: 'duplicate', color: 'cfd3d7', description: 'This issue or pull request already exists' },
              { name: 'invalid', color: 'e4e669', description: 'This does not seem right' },
              { name: 'wontfix', color: 'ffffff', description: 'This will not be worked on' },
              { name: 'stale', color: 'fef2c0', description: 'Issues or PRs that have been inactive for a while' }
            ];

            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                console.log(`✅ Created label: ${label.name}`);
              } catch (error) {
                if (error.status === 422) {
                  // Label already exists, try to update it
                  try {
                    await github.rest.issues.updateLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      name: label.name,
                      color: label.color,
                      description: label.description
                    });
                    console.log(`🔄 Updated label: ${label.name}`);
                  } catch (updateError) {
                    console.log(`⚠️ Could not update label ${label.name}: ${updateError.message}`);
                  }
                } else {
                  console.log(`❌ Error creating label ${label.name}: ${error.message}`);
                }
              }
            }
